_wandb:
    value:
        cli_version: 0.23.0
        e:
            o00dmmr8goobmuwnywdmg8fg4wtisutp:
                args:
                    - --config
                    - configs/baseline.yaml
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "322121494528"
                        used: "28794413056"
                email: shivanshbansal899@gmail.com
                executable: D:\KNOWLEDGE\Aminor\.venv\Scripts\python.exe
                git:
                    commit: 64a465a0284547cbbae58c08bb57bbd0f2e0a38f
                    remote: https://github.com/Andreaswt/audio-cnn
                host: POWERKICK
                memory:
                    total: "16537804800"
                os: Windows-11-10.0.26200-SP0
                program: D:\KNOWLEDGE\Aminor\audio-cnn\main.py
                python: CPython 3.12.4
                root: D:\KNOWLEDGE\Aminor\audio-cnn
                startedAt: "2025-11-19T16:22:42.453941Z"
                writerId: o00dmmr8goobmuwnywdmg8fg4wtisutp
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 16
            "4": 3.12.4
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
data:
    value:
        batch_size: 32
        data_path: ./data/ESC-50/
        dataset_name: ESC-50
        duration: 5
        hop_length: 512
        n_fft: 2048
        n_mels: 128
        num_workers: 4
        sample_rate: 22050
logging:
    value:
        entity: null
        log_dir: ./outputs/runs
        project_name: audio-cnn-research
model:
    value:
        name: baseline_resnet
        num_classes: 50
paths:
    value:
        figures_dir: ./outputs/figures
        model_save_dir: ./outputs/models
        results_dir: ./outputs/results
training:
    value:
        epochs: 100
        freq_mask_param: 30
        lr: 0.001
        mixup_alpha: 0.2
        optimizer: adamw
        scheduler: onecycle
        seed: 42
        time_mask_param: 40
        weight_decay: 0.01
